### ISSUE TITLE
Features Accordion

### ISSUE THREAD

**Issue by VatsalP117** [hashdocs/hashdocs#40]
**Describe the bug**
To close a particular component in the features accordion, we have to open a new one to do the same. Clicking the ^ button to hide the currently active one does not work

**To Reproduce**
https://hashdocs.org/ features section

**Expected behavior**
Currently active should be hidden on clicking ^ button

**Screenshots**
https://www.loom.com/share/e53de5230e084b29922acdcb62e942b2?sid=a4c755a2-de8b-4978-99ae-a262d8de92e0

**Comment by VatsalP117** [comment]
Really loved the product and congratulations on the launch! Let me know if this isn't the intended behavior and if I can work on it

**Comment by rbkayz** [comment]
Oh thanks a lot for this. Yeah, the behavior was meant to be atleast one open at all times. The open accordion corresponds to the video on the right

Will be working on the blog pages + CMS, if interested? Or email / slack notifications

**Comment by VatsalP117** [comment]
Thank you for your response and clarification. I will try to get familiar with the codebase and then reach out to you about how I can contribute effectively. Do you have any specific documentation, resources, or guidelines to help me get started?

**Comment by rbkayz** [comment]
Check the ./CONTRIBUTING.MD

If you face issues in setting it up, let me know
